services:
  app:
    image: front-dev-p
    build:
      context: ./frontend # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
  server:
      image: back-dev-p
      build:
        context: ./backend
        dockerfile: Dockerfile
      volumes:
        - ./backend/:/usr/src/app
        - /usr/src/app/node_modules

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-container1
    depends_on:
      - app # wait for the frontend container to be started
      - server
